# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/e203_ecg/e203_ecg/project_2/project_2.srcs/sources_1/ip/weight_mem_gen_10/weight_mem_gen_10.xci
# IP: The module: 'weight_mem_gen_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/e203_ecg/e203_ecg/project_2/project_2.srcs/sources_1/ip/weight_mem_gen_10/weight_mem_gen_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_mem_gen_10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/e203_ecg/e203_ecg/project_2/project_2.srcs/sources_1/ip/weight_mem_gen_10/weight_mem_gen_10.xci
# IP: The module: 'weight_mem_gen_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/e203_ecg/e203_ecg/project_2/project_2.srcs/sources_1/ip/weight_mem_gen_10/weight_mem_gen_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_mem_gen_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
