# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10.xci
# IP: The module: 'blk_mem_gen_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10.xci
# IP: The module: 'blk_mem_gen_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
