# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Repository/SEU-ASIC-IOT-ECGAI/ECGAI_ver_3_0/accelerator/proj/ECGAI_ver_3_0/ECGAI_ver_3_0.srcs/sources_1/ip/threshold_mem/threshold_mem.xci
# IP: The module: 'threshold_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Repository/SEU-ASIC-IOT-ECGAI/ECGAI_ver_3_0/accelerator/proj/ECGAI_ver_3_0/ECGAI_ver_3_0.gen/sources_1/ip/threshold_mem/threshold_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'threshold_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Repository/SEU-ASIC-IOT-ECGAI/ECGAI_ver_3_0/accelerator/proj/ECGAI_ver_3_0/ECGAI_ver_3_0.srcs/sources_1/ip/threshold_mem/threshold_mem.xci
# IP: The module: 'threshold_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Repository/SEU-ASIC-IOT-ECGAI/ECGAI_ver_3_0/accelerator/proj/ECGAI_ver_3_0/ECGAI_ver_3_0.gen/sources_1/ip/threshold_mem/threshold_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'threshold_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
