set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN N16 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN H15 [get_ports {class[0]}]
set_property PACKAGE_PIN L15 [get_ports {class[1]}]
set_property PACKAGE_PIN J16 [get_ports {class[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {class[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {class[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {class[0]}]
create_clock -period 20.000 -waveform {0.000 10.000} [get_ports clk]
