# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/act_mem_0/act_mem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==act_mem_0 || ORIG_REF_NAME==act_mem_0} -quiet] -quiet
