# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/project/vivado/e203/EAI/project_1/project_1.srcs/sources_1/ip/reset_sys/reset_sys.xci
# IP: The module: 'reset_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/vivado/e203/EAI/project_1/project_1.srcs/sources_1/ip/reset_sys/reset_sys_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/vivado/e203/EAI/project_1/project_1.srcs/sources_1/ip/reset_sys/reset_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/vivado/e203/EAI/project_1/project_1.srcs/sources_1/ip/reset_sys/reset_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/project/vivado/e203/EAI/project_1/project_1.srcs/sources_1/ip/reset_sys/reset_sys.xci
# IP: The module: 'reset_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/vivado/e203/EAI/project_1/project_1.srcs/sources_1/ip/reset_sys/reset_sys_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/vivado/e203/EAI/project_1/project_1.srcs/sources_1/ip/reset_sys/reset_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/vivado/e203/EAI/project_1/project_1.srcs/sources_1/ip/reset_sys/reset_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
