# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/constrs/nuclei-master.xdc

# IP: ip/mmcm/mmcm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] -quiet
