# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.cache/wt [current_project]
set_property parent.project_path D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank0.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank1.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank2.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank3.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank4.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank5.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank6.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank7.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/weight.coe/bank0.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/weight.coe/bank1.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/weight.coe/bank2.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/weight.coe/bank3.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/weight.coe/bank4.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/weight.coe/bank5.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/weight.coe/bank6.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/weight.coe/bank7.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank8.coe
add_files D:/FPGA/e203_ecgV0.2/e203_ecg1/map_nsr_100_1/fmap_padding_8bit/map_bank9.coe
read_verilog D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_defines.v
set_property file_type "Verilog Header" [get_files D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_defines.v]
set_property is_global_include true [get_files D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_defines.v]
read_verilog -library xil_defaultlib {
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/config.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Configurator.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_prj/ECG_Axi_Lite_Top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/ECG_Top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/In_Out_Buffer.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Input_Regfile.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Mem_Ctrl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Output_regfile.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Output_regfile8_9.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/PEarray16_8.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Pool2IOB.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Pooling.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Pooling8.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/RCA_8bit.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Relu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Relu8.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/SPU_ECG.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/Weight_buffer.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_gpio/apb_gpio.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_spi_master/apb_spi_master.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_uart/apb_uart.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_prj/axi_lite_S00_AXI.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_biu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_clk_ctrl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_clkgate.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_core.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_cpu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_cpu_top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_dtcm_ctrl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_dtcm_ram.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_alu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_alu_bjp.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_alu_csrctrl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_alu_dpath.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_alu_lsuagu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_alu_muldiv.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_alu_rglr.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_branchslv.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_commit.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_csr.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_decode.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_disp.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_excp.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_longpwbck.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_nice.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_oitf.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_regfile.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_exu_wbck.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_ifu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_ifu_ifetch.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_ifu_ift2icb.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_ifu_litebpu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_ifu_minidec.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_irq_sync.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_itcm_ctrl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_itcm_ram.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_lsu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_lsu_ctrl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_reset_ctrl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/soc/e203_soc_top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/core/e203_srams.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_clint.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_gfcm.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_hclkgen.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_hclkgen_rstsync.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_main.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_mems.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_nice_core.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_perips.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_plic.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_pll.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_pllclkdiv.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/subsys/e203_subsys_top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_uart/io_generic_fifo.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/multl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/general/sirv_1cyc_sram_ctrl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_AsyncResetReg.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_AsyncResetRegVec.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_AsyncResetRegVec_1.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_AsyncResetRegVec_129.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_AsyncResetRegVec_36.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_DeglitchShiftRegister.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_LevelGateway.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_ResetCatchAndSync.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_ResetCatchAndSync_2.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_aon.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_aon_lclkgen_regs.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_aon_porrst.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_aon_top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_aon_wrapper.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_clint.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_clint_top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/debug/sirv_debug_csr.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/debug/sirv_debug_module.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/debug/sirv_debug_ram.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/debug/sirv_debug_rom.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_expl_axi_slv.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_flash_qspi.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_flash_qspi_top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/general/sirv_gnrl_bufs.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/general/sirv_gnrl_dffs.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/general/sirv_gnrl_icbs.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/general/sirv_gnrl_ram.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_hclkgen_regs.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/fab/sirv_icb1to16_bus.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/fab/sirv_icb1to2_bus.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/fab/sirv_icb1to8_bus.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/debug/sirv_jtag_dtm.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_jtaggpioport.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/mems/sirv_mrom.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/mems/sirv_mrom_top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_plic_man.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_plic_top.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_pmu.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_pmu_core.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_qspi_arbiter.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_qspi_fifo.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_qspi_media.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_qspi_physical.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_queue.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_queue_1.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_repeater_6.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_rtc.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/general/sirv_sim_ram.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_spi_flashmap.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/general/sirv_sram_icb_ctrl.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_tl_repeater_5.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_tlfragmenter_qspi_1.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_tlwidthwidget_qspi.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/sirv_wdog.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_spi_master/spi_master_apb_if.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_spi_master/spi_master_clkgen.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_spi_master/spi_master_controller.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_spi_master/spi_master_fifo.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_spi_master/spi_master_rx.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_spi_master/spi_master_tx.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_1/project_1.srcs/sources_ECG/imports/ECG_acc9_onlyv/u_PE.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_uart/uart_interrupt.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_uart/uart_rx.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/e203/perips/apb_uart/uart_tx.v
  D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/system.v
}
read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/mmcm/mmcm.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/mmcm/mmcm_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/mmcm/mmcm.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/mmcm/mmcm_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/reset_sys/reset_sys.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/reset_sys/reset_sys_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/reset_sys/reset_sys.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/reset_sys/reset_sys_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_00/weight_mem_gen_00.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_00/weight_mem_gen_00_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_10/weight_mem_gen_10.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_10/weight_mem_gen_10_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_20/weight_mem_gen_20.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_20/weight_mem_gen_20_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_30/weight_mem_gen_30.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_30/weight_mem_gen_30_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_40/weight_mem_gen_40.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_40/weight_mem_gen_40_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_50/weight_mem_gen_50.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_50/weight_mem_gen_50_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_60/weight_mem_gen_60.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_60/weight_mem_gen_60_ooc.xdc]

read_ip -quiet D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_70/weight_mem_gen_70.xci
set_property used_in_implementation false [get_files -all d:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/project_3/project_3.srcs/sources_1/ip/weight_mem_gen_70/weight_mem_gen_70_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/constrs/nuclei-master.xdc
set_property used_in_implementation false [get_files D:/FPGA/e203_ecgV0.2/e203_ecg1/e203_ecg/constrs/nuclei-master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top system -part xc7a200tfbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_utilization_synth.rpt -pb system_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
